import { images } from '../assets/images';

/** Community feed seed, ported from the mock's CommunityScreens.tsx. */
export const initialCommunityPosts = [
  {
    id: "post-1",
    author: "Mario Rossi",
    handle: "mariofit",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    badge: "Elite Athlete",
    timeAgo: "2 hours ago",
    image: images.communityRun,
    caption: "Just hit a personal best — 5K in 23:45! 🏅 Small wins every single day add up. Paced consistently with negative splits in the final kilometer.",
    hashtags: ["#running", "#workout", "#morningrun", "#5KPersonalRecord"],
    likesCount: 116420,
    isLiked: false,
    commentsCount: 2140,
    sharesCount: 1895,
    isBookmarked: false,
    tagCategory: "running",
    comments: [
      {
        id: "c1",
        author: "Mario Rossi",
        authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
        timeAgo: "13h",
        text: "That's awesome, bro! 🔥 What shoes are you using for your track runs?",
        likesCount: 5,
        isLiked: false,
      },
      {
        id: "c2",
        author: "Lina Health",
        authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
        timeAgo: "13h",
        text: "Congrats! I'm still struggling to break 30 minutes 😭 any pacing tips for mile 2?",
        likesCount: 2,
        isLiked: false,
      },
      {
        id: "c3",
        author: "Sam Jenkins",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        timeAgo: "13h",
        text: "You're getting faster every week! Keep up the incredible consistency 💪",
        likesCount: 8,
        isLiked: true,
        replies: [
          {
            id: "c3-r1",
            author: "Mikael Fit",
            authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
            timeAgo: "13h",
            text: "That's a strong 5K time 👏",
            likesCount: 3,
          },
        ],
      },
      {
        id: "c4",
        author: "Jane Foster",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
        timeAgo: "13h",
        text: "Love the mindset — small wins really do add up 🌱",
        likesCount: 4,
        isLiked: false,
      },
    ],
  },
  {
    id: "post-2",
    author: "Elena Rostova",
    handle: "elena.mobility",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    badge: "Yoga Coach",
    timeAgo: "4 hours ago",
    image: images.communityYoga,
    caption: "Morning outdoor deck flow with the DMV crew. Nothing beats fresh mountain air for hamstring and thoracic mobility recovery 🧘‍♀️✨",
    hashtags: ["#mobility", "#recovery", "#yogaflow", "#dmvfitness"],
    likesCount: 84320,
    isLiked: true,
    commentsCount: 940,
    sharesCount: 620,
    isBookmarked: true,
    tagCategory: "mobility",
    comments: [
      {
        id: "c2-1",
        author: "Marcus Bell",
        authorAvatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&auto=format&fit=crop&q=80",
        timeAgo: "3h",
        text: "Scapular downward rotation looking pristine! Excellent recovery session.",
        likesCount: 19,
        isLiked: true,
      },
      {
        id: "c2-2",
        author: "Alicia Nguyen",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        timeAgo: "2h",
        text: "The hip stretch sequence was a game-changer after leg day yesterday 🙌",
        likesCount: 6,
        isLiked: false,
      },
    ],
  },
  {
    id: "post-3",
    author: "David Kim",
    handle: "chefdave.fit",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    badge: "Meal Prep Pro",
    timeAgo: "6 hours ago",
    image: images.communityMeal,
    caption: "Sunday high-protein prep locked in! 4x Grilled Lemon Herb Chicken with seasoned quinoa, steamed broccoli & soft-boiled eggs. Macros: 52g P / 48g C / 14g F per box (526 kcal).",
    hashtags: ["#mealprep", "#highprotein", "#cleaneating", "#macros"],
    likesCount: 92100,
    isLiked: false,
    commentsCount: 1420,
    sharesCount: 3100,
    isBookmarked: false,
    tagCategory: "nutrition",
    comments: [
      {
        id: "c3-1",
        author: "Sarah Connor",
        authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
        timeAgo: "5h",
        text: "How do you keep the chicken so juicy all week? Air fryer or grill pan?",
        likesCount: 11,
      },
    ],
  },
];
