/**
 * Seven-day diary dataset ported verbatim from the mock's
 * components/screens/DailyScreens.tsx (Aug 25 – Aug 31, today = Aug 28).
 */
export const weeklyHistoricalData = {
  25: {
    name: "Mon",
    date: 25,
    fullDate: "Monday, Aug 25",
    isToday: false,
    isFuture: false,
    pct: 96,
    targets: { calories: 2200, protein: 195, carbs: 220, fat: 65, water: 3.0 },
    consumed: { calories: 2120, protein: 190, carbs: 215, fat: 58, waterLiters: 2.75, waterGlasses: 11 },
    workout: {
      name: "Push Day A",
      category: "Chest & Triceps",
      status: "completed",
      duration: "48 min",
      calsBurned: 2120,
      steps: 11200,
      activeMin: 52,
      statusBadge: "Completed ✓",
      statusNote: "Logged on Mon, Aug 25 · 48m duration",
    },
    meals: [
      { id: "m25-1", mealType: "breakfast", name: "Oatmeal with Whey Protein & Blueberries", serving: "1 bowl (350g)", calories: 520, protein: 42, carbs: 65, fat: 8, verified: true },
      { id: "m25-2", mealType: "lunch", name: "Grilled Salmon with Jasmine Rice & Asparagus", serving: "200g salmon + 1.5 cups rice", calories: 710, protein: 48, carbs: 72, fat: 22, verified: true },
      { id: "m25-3", mealType: "dinner", name: "Lean Ground Turkey Bolognese with Penne", serving: "1 large plate (400g)", calories: 640, protein: 52, carbs: 68, fat: 18, verified: true },
      { id: "m25-4", mealType: "snack", name: "Whey Protein Isolate with Almond Butter", serving: "1 scoop + 1 tbsp", calories: 250, protein: 28, carbs: 10, fat: 10, verified: true },
    ],
    heartRate: {
      avg: 128,
      range: "64–162",
      bars: [
        { time: "06 AM", bpm: 70, heightPct: 40 },
        { time: "07 AM", bpm: 92, heightPct: 50 },
        { time: "08 AM", bpm: 128, heightPct: 80 },
        { time: "09 AM", bpm: 162, heightPct: 98, active: true },
        { time: "10 AM", bpm: 130, heightPct: 78 },
        { time: "11 AM", bpm: 85, heightPct: 45 },
      ],
    },
  },
  26: {
    name: "Tue",
    date: 26,
    fullDate: "Tuesday, Aug 26",
    isToday: false,
    isFuture: false,
    pct: 99,
    targets: { calories: 2200, protein: 195, carbs: 220, fat: 65, water: 3.0 },
    consumed: { calories: 2190, protein: 195, carbs: 220, fat: 62, waterLiters: 3.0, waterGlasses: 12 },
    workout: {
      name: "Pull Day B",
      category: "Back & Biceps",
      status: "completed",
      duration: "45 min",
      calsBurned: 2190,
      steps: 10450,
      activeMin: 48,
      statusBadge: "Completed ✓",
      statusNote: "Logged on Tue, Aug 26 · 45m duration",
    },
    meals: [
      { id: "m26-1", mealType: "breakfast", name: "4 Scrambled Eggs with Avocado & Whole Wheat Toast", serving: "2 slices toast + 4 eggs", calories: 560, protein: 36, carbs: 40, fat: 26, verified: true },
      { id: "m26-2", mealType: "lunch", name: "Chipotle Chicken Burrito Bowl with Brown Rice", serving: "Double chicken bowl", calories: 680, protein: 54, carbs: 78, fat: 18, verified: true },
      { id: "m26-3", mealType: "dinner", name: "Grilled Sirloin Steak with Sweet Potato & Green Beans", serving: "8oz steak + sweet potato", calories: 720, protein: 60, carbs: 65, fat: 16, verified: true },
      { id: "m26-4", mealType: "snack", name: "0% Greek Yogurt with Organic Honey & Walnuts", serving: "200g yogurt + 1 tbsp honey", calories: 230, protein: 25, carbs: 27, fat: 6, verified: true },
    ],
    heartRate: {
      avg: 121,
      range: "60–152",
      bars: [
        { time: "06 AM", bpm: 68, heightPct: 38 },
        { time: "07 AM", bpm: 88, heightPct: 48 },
        { time: "08 AM", bpm: 122, heightPct: 74 },
        { time: "09 AM", bpm: 152, heightPct: 92, active: true },
        { time: "10 AM", bpm: 124, heightPct: 72 },
        { time: "11 AM", bpm: 80, heightPct: 42 },
      ],
    },
  },
  27: {
    name: "Wed",
    date: 27,
    fullDate: "Wednesday, Aug 27",
    isToday: false,
    isFuture: false,
    pct: 90,
    targets: { calories: 2200, protein: 195, carbs: 220, fat: 65, water: 3.0 },
    consumed: { calories: 1980, protein: 180, carbs: 200, fat: 55, waterLiters: 2.5, waterGlasses: 10 },
    workout: {
      name: "Leg Hypertrophy",
      category: "Glutes & Legs",
      status: "completed",
      duration: "52 min",
      calsBurned: 1980,
      steps: 9600,
      activeMin: 54,
      statusBadge: "Completed ✓",
      statusNote: "Logged on Wed, Aug 27 · 52m duration",
    },
    meals: [
      { id: "m27-1", mealType: "breakfast", name: "Egg White Omelet with Turkey Bacon & English Muffin", serving: "1 omelet + 1 muffin", calories: 490, protein: 40, carbs: 35, fat: 14, verified: true },
      { id: "m27-2", mealType: "lunch", name: "High Protein Grilled Chicken Rice Bowl", serving: "1 bowl (380g)", calories: 650, protein: 52, carbs: 64, fat: 17, verified: true },
      { id: "m27-3", mealType: "dinner", name: "Baked Cod with Roasted Potatoes & Steamed Broccoli", serving: "250g cod + potatoes", calories: 610, protein: 46, carbs: 60, fat: 12, verified: true },
      { id: "m27-4", mealType: "snack", name: "Low-fat Cottage Cheese with Fresh Pineapple", serving: "1 cup (220g)", calories: 230, protein: 22, carbs: 21, fat: 4, verified: true },
    ],
    heartRate: {
      avg: 132,
      range: "66–168",
      bars: [
        { time: "06 AM", bpm: 72, heightPct: 42 },
        { time: "07 AM", bpm: 96, heightPct: 54 },
        { time: "08 AM", bpm: 134, heightPct: 82 },
        { time: "09 AM", bpm: 168, heightPct: 99, active: true },
        { time: "10 AM", bpm: 140, heightPct: 84 },
        { time: "11 AM", bpm: 86, heightPct: 46 },
      ],
    },
  },
  28: {
    name: "Thu",
    date: 28,
    fullDate: "Thursday, Aug 28 (Today)",
    isToday: true,
    isFuture: false,
    pct: 83,
    targets: { calories: 2200, protein: 195, carbs: 220, fat: 65, water: 3.0 },
    consumed: { calories: 1820, protein: 185, carbs: 210, fat: 60, waterLiters: 1.5, waterGlasses: 6 },
    workout: {
      name: "Push Day A",
      category: "Chest & Triceps",
      status: "active",
      duration: "45 min",
      calsBurned: 1820,
      steps: 9800,
      activeMin: 45,
      statusBadge: "Active Today",
      statusNote: "Scheduled for today · Ready to start",
    },
    meals: [
      { id: "m28-1", mealType: "breakfast", name: "3 Whole Eggs + 1/2 Cup Egg Whites & Sourdough", serving: "3 eggs + 2 slices", calories: 540, protein: 38, carbs: 42, fat: 14, verified: true },
      { id: "m28-2", mealType: "lunch", name: "High Protein Chicken Rice Bowl & Greek Yogurt", serving: "350g bowl", calories: 585, protein: 44, carbs: 64, fat: 17, verified: true },
      { id: "m28-3", mealType: "snack", name: "Whey Protein Isolate (1 scoop) & Banana", serving: "1 shake + 1 fruit", calories: 245, protein: 22, carbs: 34, fat: 2.5, verified: true },
    ],
    heartRate: {
      avg: 124,
      range: "62–156",
      bars: [
        { time: "06 AM", bpm: 72, heightPct: 40 },
        { time: "07 AM", bpm: 95, heightPct: 55 },
        { time: "08 AM", bpm: 120, heightPct: 75 },
        { time: "09 AM", bpm: 156, heightPct: 95, active: true },
        { time: "10 AM", bpm: 135, heightPct: 80 },
        { time: "11 AM", bpm: 88, heightPct: 48 },
      ],
    },
  },
  29: {
    name: "Fri",
    date: 29,
    fullDate: "Friday, Aug 29",
    isToday: false,
    isFuture: true,
    pct: 0,
    targets: { calories: 1950, protein: 185, carbs: 170, fat: 58, water: 3.0 },
    consumed: { calories: 0, protein: 0, carbs: 0, fat: 0, waterLiters: 0, waterGlasses: 0 },
    workout: {
      name: "Pull Day B",
      category: "Back & Core",
      status: "future",
      duration: "45 min",
      calsBurned: 0,
      steps: 0,
      activeMin: 0,
      statusBadge: "Scheduled for Friday",
      statusNote: "📅 Unlocks on Friday, Aug 29",
    },
    meals: [],
    heartRate: {
      avg: 0,
      range: "--",
      bars: [],
    },
  },
  30: {
    name: "Sat",
    date: 30,
    fullDate: "Saturday, Aug 30",
    isToday: false,
    isFuture: true,
    pct: 0,
    targets: { calories: 2200, protein: 195, carbs: 220, fat: 65, water: 3.0 },
    consumed: { calories: 0, protein: 0, carbs: 0, fat: 0, waterLiters: 0, waterGlasses: 0 },
    workout: {
      name: "Leg Day",
      category: "Posterior Chain",
      status: "future",
      duration: "50 min",
      calsBurned: 0,
      steps: 0,
      activeMin: 0,
      statusBadge: "Scheduled for Saturday",
      statusNote: "📅 Unlocks on Saturday, Aug 30",
    },
    meals: [],
    heartRate: {
      avg: 0,
      range: "--",
      bars: [],
    },
  },
  31: {
    name: "Sun",
    date: 31,
    fullDate: "Sunday, Aug 31",
    isToday: false,
    isFuture: true,
    pct: 0,
    targets: { calories: 2000, protein: 180, carbs: 180, fat: 60, water: 3.0 },
    consumed: { calories: 0, protein: 0, carbs: 0, fat: 0, waterLiters: 0, waterGlasses: 0 },
    workout: {
      name: "Active Recovery",
      category: "Mobility Flow",
      status: "future",
      duration: "30 min",
      calsBurned: 0,
      steps: 0,
      activeMin: 0,
      statusBadge: "Scheduled for Sunday",
      statusNote: "📅 Unlocks on Sunday, Aug 31",
    },
    meals: [],
    heartRate: {
      avg: 0,
      range: "--",
      bars: [],
    },
  },
};
