/** Search results dataset, ported from the mock's SearchFoodScreen. */
export const searchFoodDatabase = [
  {
    id: "f1",
    name: "Chicken Breast, grilled",
    source: "Generic USDA · 100g",
    baseServing: "100g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    verified: true,
    category: "Protein",
    badge: "High Protein",
  },
  {
    id: "f2",
    name: "Chicken Breast, roasted & seasoned",
    source: "Generic USDA · 100g",
    baseServing: "100g",
    calories: 177,
    protein: 30,
    carbs: 0,
    fat: 5.4,
    verified: true,
    category: "Protein",
    badge: "Lean Meat",
  },
  {
    id: "f3",
    name: "High Protein Chicken Rice Bowl",
    source: "Your Saved Recipe · 1 bowl",
    baseServing: "1 serving (450g)",
    calories: 585,
    protein: 52,
    carbs: 64,
    fat: 17,
    verified: true,
    category: "Meals",
    badge: "My Recipe",
  },
  {
    id: "f4",
    name: "Chicken Biryani, homemade",
    source: "Community Verified · 1 plate",
    baseServing: "1 plate (380g)",
    calories: 620,
    protein: 34,
    carbs: 74,
    fat: 20,
    verified: true,
    category: "Meals",
    badge: "Community",
  },
  {
    id: "f5",
    name: "Chobani 0% Greek Yogurt, Plain",
    source: "Barcode Verified · 170g",
    baseServing: "1 cup (170g)",
    calories: 120,
    protein: 20,
    carbs: 6,
    fat: 0,
    verified: true,
    category: "Protein",
    badge: "Zero Fat",
  },
  {
    id: "f6",
    name: "Beef & Rice Meal Prep Bowl",
    source: "Your Saved Recipe · 1 bowl",
    baseServing: "1 bowl (420g)",
    calories: 540,
    protein: 41,
    carbs: 48,
    fat: 19,
    verified: true,
    category: "Meals",
    badge: "Meal Prep",
  },
  {
    id: "f7",
    name: "Atlantic Salmon Fillet, grilled",
    source: "USDA Verified · 150g",
    baseServing: "1 fillet (150g)",
    calories: 310,
    protein: 34,
    carbs: 0,
    fat: 18,
    verified: true,
    category: "Protein",
    badge: "Omega-3",
  },
  {
    id: "f8",
    name: "Organic Jasmine White Rice, cooked",
    source: "USDA Verified · 1 cup",
    baseServing: "1 cup (180g)",
    calories: 210,
    protein: 4.5,
    carbs: 45,
    fat: 0.5,
    verified: true,
    category: "Carbs",
    badge: "Clean Carbs",
  },
];
